# Path to your Oh My Zsh installation
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"

# Plugins
plugins=(
  zsh-autosuggestions
)

# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Oh My PosH (PowerShell-style prompt)
export PATH=$PATH:$HOME/.local/bin
eval "$(oh-my-posh init zsh --config ~/.poshthemes/star.omp.json)"

# fnm
FNM_PATH="/home/isakidev/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "$(fnm env --shell zsh)"
fi


# Load hooks and add gap between prompts
autoload -Uz add-zsh-hook

__first_prompt=true

prompt_spacing() {
  if [[ "$__first_prompt" == true ]]; then
    __first_prompt=false
  else
    print
  fi
}

add-zsh-hook precmd prompt_spacing
