# Path to your Oh My Zsh installation
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"

# Plugins
plugins=(
  zsh-autosuggestions
)

# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Oh My PosH (PowerShell-style prompt)
export PATH=$PATH:$HOME/.local/bin
eval "$(oh-my-posh init zsh --config ~/.poshthemes/star.omp.json)"

# fnm
FNM_PATH="/home/isakidev/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "$(fnm env --shell zsh)"
fi
