#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

# oh-my-posh
export PATH=$PATH:/home/isakidev/.local/bin
eval "$(oh-my-posh init bash --config ~/.poshthemes/catppuccin.omp.json)"
