-- Generated by HyprMod

-- Settings
hl.config({
    input = {
        accel_profile = "flat",
        sensitivity = -0.6,
    },
})

-- Monitors
hl.monitor({
    output = "DP-2",
    disabled = false,
    mode = "2560x1440@280.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "DP-3",
    disabled = false,
    mode = "1920x1080@165.00Hz",
    position = "2560x180",
    scale = 1,
    cm = "srgb",
})
