splash = false

# OLED
wallpaper {
	monitor = DP-2
	path = $HOME/media/images/wallpapers/solid.jpg
	fit_mode = cover
}

# IPS
wallpaper {
	monitor = DP-3
	path = $HOME/media/images/wallpapers/wallpaper3.jpg
	fit_mode = cover
}